name: Test Common Libraries

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        package: [util, settings, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install commons
        uses: ./.github/actions/install-common
      - name: Lint
        run: npm run lint
        working-directory: ./common/${{ matrix.package }}
      - name: Test
        run: npm test
        working-directory: ./common/${{ matrix.package }}
